version: 2

updates:
    -   package-ecosystem: composer
        directory: "/"
        schedule:
            interval: daily
        open-pull-requests-limit: 3
        allow:
            -   dependency-type: direct
            -   dependency-type: indirect
        registries:
            - git-github-com

    -   package-ecosystem: docker
        directory: "/"
        schedule:
            interval: daily
        open-pull-requests-limit: 3
        registries:
            - git-github-com
