version: 2

updates:
    -   package-ecosystem: composer
        directory: "/"
        schedule:
            interval: daily
        open-pull-requests-limit: 1
        allow:
            -   dependency-type: all

    -   package-ecosystem: docker
        directory: "/"
        schedule:
            interval: daily
        open-pull-requests-limit: 3

    -   package-ecosystem: npm
        directory: "/crm"
        schedule:
            interval: daily
        open-pull-requests-limit: 1

    -   package-ecosystem: docker
        directory: "/crm"
        schedule:
            interval: daily
        open-pull-requests-limit: 3
