csa_guzzle:
    profiler: '%kernel.debug%'
    clients:
        ixora_ws:
            config: # you can specify the options as in http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client
                base_uri: http://ws.ixora-auto.ru
                headers:
                    Accept: application/xml
            middleware:
                - 'ixora_auth'
                - 'ixora_logger'

services:
    guzzle.middleware.ixora_auth:
        class: Closure
        autowire: false
        factory: ['App\Partner\Ixora\GuzzleMiddleware', authQuery]
        arguments:
            - '%env(IXORA_AUTH_CODE)%'
        tags:
            - { name: csa_guzzle.middleware, alias: ixora_auth }

    guzzle.middleware.ixora_logger:
        class: Closure
        autowire: false
        factory: ['App\Partner\Ixora\GuzzleMiddleware', logErrors]
        arguments:
            - '@logger'
        tags:
            - { name: csa_guzzle.middleware, alias: ixora_logger }
