mercure:
    enable_profiler: false
    hubs:
        default:
            url: 'http:%mercure.hub.url%'
            jwt_provider: App\Mercure\JwtProvider

parameters:
    mercure.hub.url: '%env(MERCURE_HUB_URL)%'
    env(MERCURE_HUB_URL): //mercure.automagistre.ru/.well-known/mercure
