services:
    _defaults:
        public: false
        autowire: true

    NumberFormatter: '@number.formatter'
    number.formatter:
        class: NumberFormatter
        autowire: false
        arguments:
            - '%locale%'
            - !php/const NumberFormatter::CURRENCY

    Money\Currencies: '@Money\Currencies\ISOCurrencies'
    Money\Currencies\ISOCurrencies: ~

    Money\MoneyFormatter: '@Money\Formatter\IntlMoneyFormatter'
    Money\Formatter\IntlMoneyFormatter: ~

