swiftmailer:
    transport: "%env(MAILER_TRANSPORT)%"
    host:      "%env(MAILER_HOST)%"
    username:  "%env(MAILER_USER)%"
    password:  "%env(MAILER_PASSWORD)%"
    spool:     { type: memory }

parameters:
    env(MAILER_TRANSPORT): null
    env(MAILER_HOST): null
    env(MAILER_USER): null
