---
kind: pipeline
type: docker
name: deploy

trigger:
    branch:
        - master
        - rc
        - ff
    event:
        - push

clone:
    depth: 0

volumes:
    -   name: docker.sock
        host:
            path: /var/run/docker.sock
    -   name: env
        host:
            path: /opt/secrets/automagistre

steps:
    -   name: check deploy
        image: automagistre/git:stable
        commands:
            - \[ "${DRONE_COMMIT_SHA}" == "$$(git ls-remote origin ${DRONE_COMMIT_BRANCH} | awk '{ print $1}')" ] || exit 78

    -   name: deploy
        image: automagistre/docker-compose:stable
        volumes:
            -   name: env
                path: /drone/src/.env
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - docker-compose --file .swarm.yml config | docker stack deploy --prune --with-registry-auth --resolve-image never --compose-file - automagistre
        environment:
            VERSION: ${DRONE_BUILD_NUMBER}
        depends_on:
            - check deploy

---
kind: pipeline
type: docker
name: delete

trigger:
    branch:
        - rc
        - test
        - ff
    event:
        - push
    status:
        - success
        - failure

depends_on:
    - deploy

clone:
    depth: 0

steps:
    -   name: delete branch
        image: automagistre/git:stable
        commands:
            - git remote set-url origin ${DRONE_GIT_SSH_URL}
            - mkdir -p ~/.ssh -m 700
            - ssh-keyscan github.com >> ~/.ssh/known_hosts
            - echo "$GIT_SSH_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - git push origin --delete ${DRONE_COMMIT_BRANCH}
        environment:
            GIT_SSH_KEY:
                from_secret: GIT_SSH_KEY

---
kind: pipeline
type: docker
name: dependabot

trigger:
    branch:
        - master
    event:
        - pull_request
clone:
    disable: true

steps:
    -   name: check is dependabot
        image: automagistre/git:stable
        pull: if-not-exists
        commands:
            - \[ "dependabot[bot]" == ${DRONE_COMMIT_AUTHOR} ] || exit 78

    -   name: clone
        image: automagistre/git:stable
        pull: if-not-exists
        commands:
            - git clone --depth 2 -b ${DRONE_SOURCE_BRANCH} ${DRONE_REMOTE_URL} .
            - git reset --hard ${DRONE_COMMIT_SHA}
        depends_on:
            - check is dependabot

    -   name: automerge
        image: automagistre/github-cli:stable
        pull: if-not-exists
        commands:
            - gh pr merge ${DRONE_PULL_REQUEST} --auto --rebase
        environment:
            GITHUB_TOKEN:
                from_secret: GITHUB_TOKEN
        depends_on:
            - clone

    -   name: rebase
        image: automagistre/github-cli:stable
        pull: if-not-exists
        commands:
            - |
                if [ "$$(git rev-parse HEAD^1)" != "$$(git ls-remote origin ${DRONE_COMMIT_BRANCH} | awk '{ print $1}')" ]
                then
                    gh pr comment ${DRONE_PULL_REQUEST} --body "@dependabot rebase"
                fi
        environment:
            GITHUB_TOKEN:
                from_secret: GITHUB_TOKEN
        depends_on:
            - clone
