---
kind: pipeline
type: docker
name: default

clone:
    depth: 1

steps:
    -   name: build base
        image: docker:19.03.6
        volumes:
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - docker build -t "automagistre/tenant-php:base" --progress=plain --target php-base .
            - docker build -t "automagistre/tenant-nginx:base" --progress=plain --target nginx-base .
        environment:
            DOCKER_BUILDKIT: '1'

    -   name: build prod
        image: docker:19.03.6
        volumes:
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - docker build -t "automagistre/tenant-php:${DRONE_BUILD_NUMBER}" --progress=plain --target php .
            - docker build -t "automagistre/tenant-nginx:${DRONE_BUILD_NUMBER}" --progress=plain --target nginx .
        environment:
            DOCKER_BUILDKIT: '1'
        depends_on:
            - build base

    -   name: push base
        image: docker:19.03.6
        volumes:
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - docker login --username "$USERNAME" --password "$PASSWORD"
            - docker push automagistre/tenant-php:base
            - docker push automagistre/tenant-nginx:base
        environment:
            USERNAME:
                from_secret: HUB_USER
            PASSWORD:
                from_secret: HUB_TOKEN
        when:
            branch: [ master ]
        depends_on:
            - build base

    -   name: install
        image: automagistre/tenant-php:base
        commands:
            - echo APP_ENV=test >> .env
            - echo APP_DEBUG=1 >> .env
            - composer install --no-interaction --no-progress --classmap-authoritative
            - bin/console cache:warmup
            - bin/console assets:install public
        depends_on:
            - build base

    -   name: php-cs-fixer
        image: automagistre/tenant-php:base
        commands:
            - vendor/bin/php-cs-fixer fix --dry-run --diff-format udiff --using-cache=no
        when:
            branch:
                exclude: [ master ]
        depends_on:
            - install

    -   name: composer normalize
        image: automagistre/tenant-php:base
        commands:
            - composer normalize --dry-run
        when:
            branch:
                exclude: [ master ]
        depends_on:
            - install

    -   name: blank end line
        image: automagistre/tenant-php:base
        commands:
            - >-
                find .
                -not -path "./public/*"
                -not -path "./.idea/*"
                -not -path "./var/*"
                -not -path "./vendor/*"
                -type f -exec grep -Iq . {} \; -and -print0
                | xargs -0 -L1 bash -c 'test -z "$(tail -c 1 "$0")"
                || (echo "No new line at end of $0" && exit 1)'
                || exit 1
        when:
            branch:
                exclude: [ master ]
        depends_on:
            - install

    -   name: symfony requirements
        image: automagistre/tenant-php:base
        commands:
            - vendor/bin/requirements-checker
        when:
            branch:
                exclude: [ master ]
        depends_on:
            - install

    -   name: symfony security
        image: automagistre/tenant-php:base
        commands:
            - vendor/bin/security-checker security:check $APP_DIR/composer.lock
        when:
            branch:
                exclude: [ master ]
        depends_on:
            - install

    -   name: symfony linters
        image: automagistre/tenant-php:base
        commands:
            - bin/console lint:yaml config
            - bin/console lint:twig templates
        depends_on:
            - install

    -   name: phpstan
        image: automagistre/tenant-php:base
        commands:
            - vendor/bin/phpstan analyse --configuration phpstan.neon --no-progress --memory-limit=-1
        depends_on:
            - install

    -   name: psalm
        image: automagistre/tenant-php:base
        commands:
            - vendor/bin/psalm --show-info=false --no-progress
        when:
            event: [ push ]
        depends_on:
            - install

    -   name: migration
        image: automagistre/tenant-php:base
        commands:
            - $$WAIT_FOR_IT db:5432
            - bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
        depends_on:
            - install

    -   name: fixtures
        image: automagistre/tenant-php:base
        commands:
            - bin/console doctrine:fixtures:load --no-interaction
        depends_on:
            - migration

    -   name: doctrine validate
        image: automagistre/tenant-php:base
        commands:
            - bin/console doctrine:schema:validate
        depends_on:
            - migration

    -   name: phpunit
        image: automagistre/tenant-php:base
        commands:
            - vendor/bin/paratest --log-junit=var/junit.xml --coverage-clover=var/clover.xml
        depends_on:
            - fixtures

    -   name: sonarqube
        image: aosapps/drone-sonar-plugin
        settings:
            sonar_host: https://sonarqube.automagistre.ru
            sonar_token:
                from_secret: SONAR_TOKEN
        when:
            branch: master
        depends_on:
            - phpunit

    -   name: check deploy
        image: alpine/git:1.0.7
        commands:
            - \[ "${DRONE_COMMIT_SHA}" == "$$(git ls-remote origin ${DRONE_COMMIT_BRANCH} | awk '{ print $1}')" ] || exit 78
        when:
            branch: [ master, rc ]
        depends_on:
            - build prod
            - phpunit
            - phpstan
            - psalm
            - symfony requirements
            - doctrine validate

    -   name: deploy
        image: docker/compose:1.25.0-alpine
        volumes:
            -   name: env
                path: /drone/src/.env
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - >-
                cat .tenants | while read tenant; do
                export TENANT=$tenant
                && mkdir -p /opt/am/db/tenant/$tenant
                && docker-compose --file .swarm.yml config | docker stack deploy --prune --with-registry-auth --compose-file - tenant_$tenant
                ; done
        environment:
            VERSION: ${DRONE_BUILD_NUMBER}
        when:
            branch: [ master, rc ]
        depends_on:
            - check deploy

    -   name: remove branch
        image: alpine/git:1.0.7
        commands:
            - git remote set-url origin ${DRONE_GIT_SSH_URL}
            - mkdir -p ~/.ssh -m 700
            - ssh-keyscan github.com >> ~/.ssh/known_hosts
            - echo "$GIT_SSH_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - git push origin --delete ${DRONE_COMMIT_BRANCH}
        environment:
            GIT_SSH_KEY:
                from_secret: GIT_SSH_KEY
        when:
            branch:
                - rc
                - test
        depends_on:
            - check deploy

services:
    -   name: db
        image: postgres:12.2
        environment:
            POSTGRES_DB: db_test
            POSTGRES_USER: db
            POSTGRES_PASSWORD: db
        tmpfs:
            - /var/lib/postgresql/data

volumes:
    -   name: docker.sock
        host:
            path: /var/run/docker.sock
    -   name: env
        host:
            path: /opt/secrets/automagistre
