clone:
    git:
        image: plugins/git
        depth: 1

pipeline:
    build app:
        group: build
        image: docker:18.06.1-ce
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - >-
                docker build -t "automagistre/app:${DRONE_BUILD_NUMBER}"
                --build-arg APP_VERSION="$DRONE_BUILD_NUMBER"
                --build-arg APP_BUILD_TIME="`date --rfc-2822`"
                --build-arg APP_CACHE="test"
                .

    validate php-cs-fixer:
        group: validate
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - >-
                php-cs-fixer fix
                --config=./.php_cs.dist
                --verbose
                --dry-run
                --using-cache=no
        when:
            branch:
                exclude: master

    validate blank end line:
        group: validate
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - >-
                find .
                -not -path "./public/*"
                -not -path "./.idea/*"
                -type f -exec grep -Iq . {} \; -and -print0
                | xargs -0 -L1 bash -c 'test -z "$(tail -c 1 "$0")"
                || (echo "No new line at end of $0" && exit 1)'
                || exit 1
        when:
            branch:
                exclude: master

    validate symfony requirements:
        group: validate
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - /docker-entrypoint.sh requirements-checker
        environment:
            APP_ENV: 'prod'
            APP_DEBUG: '0'
        when:
            branch:
                exclude: [ master ]

    validate symfony security:
        group: validate
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - /docker-entrypoint.sh security-checker security:check $APP_DIR/composer.lock
        environment:
            APP_ENV: 'test'
            APP_DEBUG: '0'
        when:
            branch:
                exclude: [ master ]

    validate phpstan:
        group: validate
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - cd "$APP_DIR"
            - /docker-entrypoint.sh php -d memory_limit=-1 vendor/bin/phpstan analyse --configuration phpstan.neon --no-progress
        environment:
            APP_ENV: 'test'
            APP_DEBUG: '1'

    validate doctrine:
        group: validate
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - $$WAIT_FOR_IT mysql:3306
            - /docker-entrypoint.sh console doctrine:schema:create
        environment:
            APP_ENV: 'test'
            APP_DEBUG: '0'

    test phpunit:
        group: test
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - cd "$APP_DIR"
            - /docker-entrypoint.sh
            - paratest --processes=$(grep -c ^processor /proc/cpuinfo || 4)
        environment:
            APP_ENV: 'test'
            APP_DEBUG: '0'

    build app prod:
        group: deploy
        image: docker:18.06.1-ce
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - >-
                docker build -t "automagistre/app:${DRONE_BUILD_NUMBER}"
                --build-arg APP_VERSION="$DRONE_BUILD_NUMBER"
                --build-arg APP_BUILD_TIME="`date --rfc-2822`"
                --build-arg APP_CACHE="prod"
                .
        when:
            event: push
            branch: master
            status: success

    deploy:
        image: docker/compose:1.23.1
        commands:
            - docker-compose --file infrastructure/docker-stack.automagistre.yml config | docker stack deploy --prune --with-registry-auth --compose-file - automagistre
        when:
            event: push
            branch: master
            status: success

services:
    mysql:
        image: mariadb:10.3.10
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'db'
            MYSQL_PASSWORD: 'db'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        tmpfs:
            - /var/lib/mysql
