clone:
    git:
        image: plugins/git
        depth: 1

_docker: &docker
    image: docker
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ HUB_LOGIN, HUB_PASSWORD ]

_when_master: &when-master
    when:
        event: push
        branch: master
        status: success

pipeline:
    build app:
        <<: *docker
        group: build
        commands:
            - >-
                docker build -t "automagistre/automagistre:${DRONE_BUILD_NUMBER}"
                --label build=${DRONE_BUILD_NUMBER}
                --build-arg APP_BUILD="$DRONE_BUILD_NUMBER"
                --build-arg APP_BUILD_TIME="`date --rfc-2822`"
                .

    validate php-cs-fixer:
        group: validate
        image: automagistre/automagistre:${DRONE_BUILD_NUMBER}
        commands:
            - >-
                php-cs-fixer fix
                --config=./.php_cs.dist
                --verbose
                --dry-run
                --using-cache=no
        when:
            branch:
                exclude: master

    validate blank end line:
        group: validate
        image: automagistre/automagistre:${DRONE_BUILD_NUMBER}
        commands:
            - >-
                find . -type f -exec grep -Iq . {} \; -and -print0
                | xargs -0 -L1 bash -c 'test -z "$(tail -c 1 "$0")"
                || (echo "No new line at end of $0" && exit 1)'
                || exit 1
        when:
            branch:
                exclude: master

    validate phpstan:
        group: validate
        image: automagistre/automagistre:${DRONE_BUILD_NUMBER}
        commands:
            - cd "$APP_DIR"
            - php -d memory_limit=-1 vendor/bin/phpstan analyse --level 5 --configuration phpstan.neon --no-progress src tests
        when:
            branch:
                exclude: master

    validate symfony requirements:
        group: validate
        image: automagistre/automagistre:${DRONE_BUILD_NUMBER}
        commands:
            - /docker-entrypoint.sh symfony_requirements
        environment:
            APP_ENV: 'test'
        when:
            branch:
                exclude: master

#    validate doctrine: &validate-doctrine
#        group: validate
#        image: automagistre/automagistre:${DRONE_BUILD_NUMBER}
#        commands:
#            - /docker-entrypoint.sh console doctrine:schema:validate
#        environment:
#            APP_ENV: 'test'
#            MIGRATIONS: 'true'
#            WAIT_HOSTS: 'mysql:3306'

    validate doctrine: &validate-doctrine
        group: validate
        image: automagistre/automagistre:${DRONE_BUILD_NUMBER}
        commands:
            - /docker-entrypoint.sh console doctrine:schema:create
        environment:
            APP_ENV: 'test'
            MIGRATIONS: 'false'
            WAIT_HOSTS: 'mysql:3306'

    test phpunit: &test-phpunit
        group: test
        image: automagistre/automagistre:${DRONE_BUILD_NUMBER}
        commands:
            - cd "$APP_DIR"
            - /docker-entrypoint.sh phpunit
        environment:
            APP_ENV: 'test'
            FIXTURES: 'false'

    clean:
        <<: *docker
        group: deploy
        commands:
            - docker rmi --force `docker images --filter before=automagistre/automagistre:${DRONE_BUILD_NUMBER} --format "{{ .Repository }}:{{ .Tag }}" automagistre/automagistre`
        when:
            branch: master
            status: [ success, failure ]

    deploy: &deploy_service
        <<: *docker
        <<: *when-master
        commands:
            - docker service update --detach=false --image "automagistre/automagistre:${DRONE_BUILD_NUMBER}" automagistre

services:
    mysql:
        image: mariadb:10.1.23
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'db'
            MYSQL_PASSWORD: 'db'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
