clone:
    git:
        image: plugins/git
        depth: 1

pipeline:
    build app:
        group: build
        image: docker:18.06.1-ce
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - >-
                docker build -t "automagistre/app:${DRONE_BUILD_NUMBER}"
                --build-arg APP_ENV="test"
                --build-arg APP_DEBUG="1"
                --build-arg APP_VERSION="$DRONE_BUILD_NUMBER"
                --build-arg APP_BUILD_TIME="`date --rfc-2822`"
                --target app
                .

    validate php-cs-fixer:
        group: validate
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - >-
                php-cs-fixer fix
                --config=./.php_cs.dist
                --verbose
                --dry-run
                --using-cache=no
        when:
            branch:
                exclude: master

    validate blank end line:
        group: validate
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - >-
                find .
                -not -path "./public/*"
                -not -path "./.idea/*"
                -type f -exec grep -Iq . {} \; -and -print0
                | xargs -0 -L1 bash -c 'test -z "$(tail -c 1 "$0")"
                || (echo "No new line at end of $0" && exit 1)'
                || exit 1
        when:
            branch:
                exclude: master

    validate symfony requirements:
        group: validate
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - requirements-checker
        when:
            branch:
                exclude: [ master ]

    validate symfony security:
        group: validate
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - security-checker security:check $APP_DIR/composer.lock
        when:
            branch:
                exclude: [ master ]

    validate phpstan:
        group: validate
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - cd "$APP_DIR"
            - phpstan analyse --configuration phpstan.neon --no-progress

    validate doctrine:
        group: validate
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - $$WAIT_FOR_IT landlord:3306
            - console doctrine:schema:create --em=landlord
        environment:
            MYSQL_PASSWORD: 'db'

    test phpunit:
        group: test
        image: automagistre/app:${DRONE_BUILD_NUMBER}
        commands:
            - cd "$APP_DIR"
            - paratest --processes=$(grep -c ^processor /proc/cpuinfo || 4)
        environment:
            MYSQL_PASSWORD: 'db'

    build app prod:
        group: deploy
        image: docker:18.06.1-ce
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - >-
                docker build -t "automagistre/app:${DRONE_BUILD_NUMBER}"
                --build-arg APP_ENV="prod"
                --build-arg APP_DEBUG="0"
                --build-arg APP_VERSION="$DRONE_BUILD_NUMBER"
                --build-arg APP_BUILD_TIME="`date --rfc-2822`"
                --target app
                .
            - >-
                docker build -t "automagistre/app-nginx:${DRONE_BUILD_NUMBER}"
                --target nginx
                .
        when:
            event: push
            branch: master
            status: success

    deploy:
        image: docker/compose:1.23.1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - cd infrastructure
            - docker-compose --file docker-stack.automagistre.yml config | docker stack deploy --prune --with-registry-auth --compose-file - automagistre
            - docker stack deploy --prune --with-registry-auth --compose-file docker-stack.redirects.yml redirect
        when:
            event: push
            branch: master
            status: success

services:
    landlord:
        image: mariadb:10.3.10
        environment:
            MYSQL_DATABASE: 'landlord'
            MYSQL_USER: 'db'
            MYSQL_PASSWORD: 'db'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        tmpfs:
            - /var/lib/mysql
    tenant:
        image: mariadb:10.3.10
        environment:
            MYSQL_DATABASE: 'tenant'
            MYSQL_USER: 'db'
            MYSQL_PASSWORD: 'db'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        tmpfs:
            - /var/lib/mysql
