version: '3.7'

services:
    nginx:
        image: automagistre/tenant-nginx:${VERSION}
        networks:
            - default
            - traefik
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: dnsrr
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.automagistre-tenant-${TENANT}.rule=Host(`${TENANT}.automagistre.ru`)"
                - "traefik.http.routers.automagistre-tenant-${TENANT}.entrypoints=websecure"
                - "traefik.http.routers.automagistre-tenant-${TENANT}.tls=true"
                - "traefik.http.routers.automagistre-tenant-${TENANT}.tls.certresolver=leresolver"
                - "traefik.http.services.automagistre-tenant-${TENANT}-service.loadbalancer.server.port=80"

    php-fpm: &php-fpm
        image: automagistre/tenant-php:${VERSION}
        networks:
            - default
            - nsq
        environment:
            APP_SECRET: ${APP_SECRET}
            DATABASE_PASSWORD: ${DB_PASSWORD}
            SENTRY_DSN: ${SENTRY_DSN}
            SMSAERO_AUTH: ${SMSAERO_AUTH}
            TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
            TENANT: ${TENANT}
            GOOGLE_CREDENTIALS_FILE: ${GOOGLE_CREDENTIALS_FILE}
        stop_grace_period: 120s
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: dnsrr
            restart_policy:
                condition: any
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first

    cron:
        <<: *php-fpm
        command: console cron:start --blocking
        healthcheck:
            disable: true
        deploy:
            mode: replicated
            replicas: 1

    messenger:
        <<: *php-fpm
        command: console messenger:consume async -vv
        healthcheck:
            disable: true
        deploy:
            mode: replicated
            replicas: 1

    migration:
        <<: *php-fpm
        command: console doctrine:migrations:migrate --no-interaction --allow-no-migration --all-or-nothing=true
        healthcheck:
            disable: true
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure

    db:
        image: postgres:12.2
        volumes:
            -   type: bind
                source: /opt/am/db/tenant/${TENANT}
                target: /var/lib/postgresql/data
            -   type: bind
                source: /opt/am/db/backups
                target: /backups
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: db
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        deploy:
            mode: global
            update_config:
                failure_action: rollback
                parallelism: 1
                delay: 5s
        healthcheck:
            test: pg_isready
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 10s

    memcached:
        image: memcached:1.6.9-alpine
        healthcheck:
            test: nc -z 127.0.0.1 11211
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 5s

networks:
    traefik:
        external: true
        name: traefik
    default:
        driver: overlay
        name: tenant_${TENANT}
    nsq:
        external: true
        name: nsq
