version: "3.8"

services:
  nginx:
    image: harbor.automagistre.ru/automagistre/crm:nginx-${VERSION:-latest}
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname == automagistre-stack
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
        monitor: 60s
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: stop-first
    environment:
      PHP_FPM_HOST: automagistre-crm_php-fpm
    networks:
      - automagistre-crm
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.automagistre-crm.rule=Host(`crm.automagistre.ru`)"
      - "traefik.http.routers.automagistre-crm.entrypoints=websecure"
      - "traefik.http.routers.automagistre-crm.tls=true"
      - "traefik.http.routers.automagistre-crm.tls.certresolver=letsencrypt"
      - "traefik.http.routers.automagistre-crm-redirect.rule=Host(`r.automagistre.ru`)"
      - "traefik.http.routers.automagistre-crm-redirect.entrypoints=websecure"
      - "traefik.http.routers.automagistre-crm-redirect.tls=true"
      - "traefik.http.routers.automagistre-crm-redirect.tls.certresolver=letsencrypt"
      - "traefik.http.routers.automagistre-crm-callback.rule=Host(`callback.automagistre.ru`)"
      - "traefik.http.routers.automagistre-crm-callback.entrypoints=websecure"
      - "traefik.http.routers.automagistre-crm-callback.tls=true"
      - "traefik.http.routers.automagistre-crm-callback.tls.certresolver=letsencrypt"
      - "traefik.http.services.automagistre-crm.loadbalancer.server.port=80"
      - "traefik.swarm.network=traefik-public"

  php-fpm: &php-fpm
    image: harbor.automagistre.ru/automagistre/crm:php-${VERSION:-latest}
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.hostname == automagistre-stack
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
        monitor: 60s
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: stop-first
    networks:
      - automagistre-crm
    environment:
      APP_SECRET: ${APP_SECRET}
      APP_VERSION: ${VERSION:-latest}
      POSTGRES_HOST: ${POSTGRES_HOST:-192.168.55.80}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: ${REDIS_HOST:-192.168.55.80}
      REDIS_PORT: ${REDIS_PORT:-6379}
      SENTRY_DSN: ${SENTRY_DSN}
      SMSAERO_AUTH: ${SMSAERO_AUTH}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      GOOGLE_CREDENTIALS_FILE: ${GOOGLE_CREDENTIALS_FILE}
      KEYCLOAK_CLI_CLIENT_SECRET: ${KEYCLOAK_CLI_CLIENT_SECRET}
      KEYCLOAK_CRM_OAUTH_CLIENT_SECRET: ${KEYCLOAK_CRM_OAUTH_CLIENT_SECRET}
      NSQ_HOST: nsqd
    volumes:
      - /etc/hostname:/etc/hostname:ro
    stop_grace_period: 120s

  cron:
    <<: *php-fpm
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == automagistre-stack
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: console cron:start --blocking
    healthcheck:
      disable: true

  messenger:
    <<: *php-fpm
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname == automagistre-stack
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: console messenger:consume async -vv
    healthcheck:
      disable: true

  nsqd:
    image: nsqio/nsq:v1.2.1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == automagistre-stack
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command:
      - /nsqd
      - -data-path=/data
      - -max-heartbeat-interval=2m
      - -msg-timeout=2m
      - -sync-every=2500
      - -sync-timeout=2s
    networks:
      - automagistre-crm
    volumes:
      # Постоянное хранилище для NSQ данных (критично для надежности)
      - type: volume
        source: nsq-data
        target: /data
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4151/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  nsq-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/docker-data/automagistre-crm/nsq

networks:
  traefik-public:
    external: true
  automagistre-crm:
    driver: overlay
    attachable: true
    name: automagistre-crm
