apiVersion: v1
kind: Service
metadata:
  name: {{ include "automagistre.fullname" . }}
  labels:
    {{- include "automagistre.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "automagistre.selectorLabels" . | nindent 4 }}
