easy_admin:
    entities:
        Order:
            class: App\Order\Entity\Order
            controller: App\Order\Controller\OrderController
            disabled_actions: ['edit', 'delete']
            templates:
                show: 'easy_admin/order/show.html.twig'
                new: 'easy_admin/order/new.html.twig'
                edit: 'easy_admin/order/edit.html.twig'
            label: 'Заказ'
            list:
                max_results: 50
                title: '{{ app.request.query.has("all") ? "Все" : "Активные" }} Заказы'
                fields:
                    - { property: 'number', label: 'Номер', template: 'easy_admin/order/field_number.html.twig' }
                    - { property: 'status', label: 'Статус', template: 'easy_admin/order/field_status.html.twig' }
                    - { property: 'createdAt', label: 'Дата начала', template: 'easy_admin/order/field_created_at.html.twig' }
                    - { property: 'carId', label: 'Автомобиль', template: 'easy_admin/field_identifier.html.twig', format: long }
                    - { property: 'customerId', label: 'Заказчик', template: 'easy_admin/field_identifier.html.twig' }
                    - { property: 'totalServicePrice', label: 'Работы', template: 'easy_admin/field_money.html.twig' }
                    - { property: 'totalPartPrice', label: 'Запчасти', template: 'easy_admin/field_money.html.twig' }
            form:
                fields:
                    - { type: 'group', label: 'Основная информация', css_class: 'col-sm-6' }
                    - { property: 'customerId', label: 'Заказчик', type: App\EasyAdmin\Form\AutocompleteType, type_options: { class: App\Customer\Entity\Operand } }
                    - { property: 'carId', label: 'Автомобиль', type: App\EasyAdmin\Form\AutocompleteType, type_options: { class: App\Car\Entity\Car } }
                    - { property: 'mileage', label: 'Пробег' }
                    - { property: 'worker', label: 'Работник', type: App\Employee\Form\EmployeeType }
                    - { type: 'group', label: 'Описание', css_class: 'col-sm-6' }
                    - { property: 'description', label: 'Описание', type: 'textarea' }
            new:
                title: 'Создать новый заказ'
            edit:
                title: 'Редактировать заказ'

        OrderPrint:
            class: App\Order\Entity\Order
            controller: App\Order\Controller\OrderPrintController
            disabled_actions: ['show', 'list', 'new', 'edit', 'autocomplete', 'search']

        OrderItemGroup:
            class: App\Order\Entity\OrderItemGroup
            controller: App\Order\Controller\OrderItemGroupController
            disabled_actions: ['show', 'list', 'search']
            templates:
                new: 'easy_admin/order_item_group/new.html.twig'
                edit: 'easy_admin/order_item_group/edit.html.twig'
            form:
                fields:
                    - { property: 'order', label: 'Заказ', type: 'text', type_options: { disabled: true } }
                    - { property: 'name', label: 'Название' }
                    - { property: 'hideParts', label: 'Скрыть запчасти от клиента' }
            new:
                form_options: { data_class: App\Order\Form\OrderGroup }

        OrderItemService:
            class: App\Order\Entity\OrderItemService
            controller: App\Order\Controller\OrderItemServiceController
            disabled_actions: ['show']
            templates:
                list: 'easy_admin/order_item_service/list.html.twig'
                new: 'easy_admin/order_item_service/new.html.twig'
                edit: 'easy_admin/order_item_service/edit.html.twig'
            list:
                fields:
                    - { property: 'order', label: 'Заказ', template: 'easy_admin/order_item_service/field_order.html.twig' }
                    - { property: 'service', label: 'Работа' }
                    - { property: 'price', label: 'Стоимость', template: 'easy_admin/field_money.html.twig' }
                    - { property: 'order.closedAt', label: 'Дата', type: 'datetime' }
                    - { property: 'order.mileage', label: 'Пробег' }
                    - { property: 'workerId', label: 'Исполнитель', template: 'easy_admin/field_identifier.html.twig' }
            edit:
                actions: ['delete']
                fields:
                    - { property: 'service', label: 'Работа' }
            form:
                fields:
                    - { property: 'order', label: 'Заказ', type: 'text', type_options: { disabled: true } }
                    - { property: 'parent', label: 'Группа', type: App\Order\Form\Type\OrderItemParentType }
                    - { property: 'service', label: 'Работа', type_options: { required: true } }
                    - { property: 'price', label: 'Стоимость', type: App\Form\Type\MoneyType }
                    - { property: 'workerId', label: 'Исполнитель', type: App\Customer\Form\WorkerType }
                    - { property: 'warranty', label: 'По гарантии?' }
                    - { property: 'discount', label: 'Скидка', type: App\Form\Type\MoneyType }
            new:
                form_options: { data_class: App\Order\Form\OrderService }

        OrderItemPart:
            class: App\Order\Entity\OrderItemPart
            controller: App\Order\Controller\OrderItemPartController
            disabled_actions: ['show', 'list', 'search']
            templates:
                new: 'easy_admin/order_item_part/new.html.twig'
                edit: 'easy_admin/order_item_part/edit.html.twig'
            edit:
                actions: ['delete']
                fields:
                    - { property: 'partId', type_options: { disabled: true } }
            form:
                fields:
                    - { property: 'order', label: 'Заказ', type: 'text', type_options: { disabled: true } }
                    - { property: 'parent', label: 'Работа / Группа', type: App\Order\Form\Type\OrderItemParentType }
                    -   property: 'partId'
                        label: 'Запчасть'
                        type: App\EasyAdmin\Form\AutocompleteType
                        type_options:
                            required: true
                            class: App\Part\Entity\Part
                    - { property: 'price', label: 'Стоимость', type: App\Form\Type\MoneyType }
                    - { property: 'quantity', label: 'Количество', type: App\Form\Type\QuantityType }
                    - { property: 'warranty', label: 'По гарантии?' }
                    - { property: 'supplier', label: 'Поставщик', type: App\Customer\Form\SellerType }
            new:
                form_options: { data_class: App\Order\Form\OrderPart }

doctrine:
    orm:
        mappings:
            order:
                type: annotation
                prefix: App\Order\Entity
                dir: '%kernel.project_dir%/src/Order/Entity'

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

