framework:
    cache:
        default_redis_provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%'

services:
    Redis:
        class: Redis
        lazy: true
        calls:
            - [ connect, [ '%env(REDIS_HOST)%', '%env(int:REDIS_PORT)%' ]]

parameters:
    env(REDIS_URL): 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%'
