services:
    cache.doctrine.query:
        class: Symfony\Component\Cache\DoctrineProvider
        arguments:
            - !service
                class: Symfony\Component\Cache\Adapter\ApcuAdapter
                arguments:
                    - doctrine_query
