services:
    cache.doctrine.query:
        class: Doctrine\Common\Cache\Psr6\DoctrineProvider
        factory: [Doctrine\Common\Cache\Psr6\DoctrineProvider, wrap]
        arguments:
            - !service
                class: Symfony\Component\Cache\Adapter\ApcuAdapter
                arguments:
                    - doctrine_query
