logout:
    path: /logout

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'
    prefix: /account

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    type: annotation
    condition: request.getHost() matches '/sto.automagistre.(ru|local)/'

app:
    resource: '../src/Controller/DefaultController.php'
    type: annotation
