easy_admin:
    entities:
        Wallet:
            class: App\Wallet\Entity\Wallet
            controller: App\Wallet\Controller\WalletController
            disabled_actions: ['show', 'search']
            list:
                title: 'Счета'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'currency', label: 'Валюта' }
                    - { property: 'useInIncome', label: 'Использовать для оплаты приходов' }
                    - { property: 'useInOrder', label: 'Использовать для начислений по заказам' }
                    - { property: 'showInLayout', label: 'Показывать в шапке' }
                    - { property: 'defaultInManualTransaction', label: 'По умолчанию в ручной проводке' }
            new:
                title: 'Создать новый счет'
                form_options: { data_class: stdClass }
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'currency', label: 'Валюта', type: App\Form\Type\CurrencyType }
                    - { property: 'useInIncome', label: 'Использовать для оплаты приходов' }
                    - { property: 'useInOrder', label: 'Использовать для начислений по заказам' }
                    - { property: 'showInLayout', label: 'Показывать в шапке' }
            edit:
                title: 'Редактировать счет'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'currency', label: 'Валюта', type: App\Form\Type\CurrencyType, type_options: { disabled: true } }
                    - { property: 'useInIncome', label: 'Использовать для оплаты приходов' }
                    - { property: 'useInOrder', label: 'Использовать для начислений по заказам' }
                    - { property: 'showInLayout', label: 'Показывать в шапке' }

        WalletTransaction:
            class: App\Wallet\Entity\WalletTransactionView
            controller: App\Wallet\Controller\TransactionController
            disabled_actions: ['show', 'delete', 'edit', 'new']
            list:
                title: 'Список проводок'
                fields:
#                    - { property: 'id', template: 'easy_admin/default/field_raw.html.twig' }
                    - { property: 'walletId', label: 'Счет', sortable: false, template: 'easy_admin/field_identifier.html.twig' }
                    - { property: 'amount', label: 'Сумма', sortable: false, template: 'easy_admin/field_money.html.twig' }
                    - { property: 'source', label: 'Описание', sortable: false, template: 'easy_admin/wallet/field_description.html.twig' }
                    - { property: 'description', label: 'Комментарий', sortable: false, template: 'easy_admin/default/field_raw.html.twig' }
                    - { property: 'createdAt', label: 'Дата', sortable: false }
                    - { property: 'createdBy', label: 'Создал', sortable: false, template: 'easy_admin/field_identifier.html.twig' }

doctrine:
    orm:
        mappings:
            wallet:
                type: annotation
                prefix: App\Wallet\Entity
                dir: '%kernel.project_dir%/src/Wallet/Entity'

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
