<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20210912133929 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $tenantCase = ' USING NULL';
        $groupCase = ' USING NULL';

        $this->addSql('ALTER TABLE appeal_calculator ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE appeal_calculator ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_calculator.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE appeal_call ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE appeal_call ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_call.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE appeal_cooperation ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE appeal_cooperation ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_cooperation.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE appeal_postpone ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE appeal_postpone ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_postpone.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE appeal_question ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE appeal_question ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_question.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE appeal_schedule ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE appeal_schedule ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_schedule.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE appeal_status ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE appeal_status ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_status.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE appeal_tire_fitting ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE appeal_tire_fitting ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_tire_fitting.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE calendar_entry ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE calendar_entry ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN calendar_entry.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE calendar_entry_deletion ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE calendar_entry_deletion ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN calendar_entry_deletion.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE calendar_entry_order ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE calendar_entry_order ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN calendar_entry_order.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE calendar_entry_order_info ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE calendar_entry_order_info ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN calendar_entry_order_info.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE calendar_entry_schedule ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE calendar_entry_schedule ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN calendar_entry_schedule.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE car ALTER tenant_group_id TYPE UUID'.$groupCase);
        $this->addSql('ALTER TABLE car ALTER tenant_group_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN car.tenant_group_id IS \'(DC2Type:tenant_group_id)\'');
        $this->addSql('ALTER TABLE car_recommendation ALTER tenant_group_id TYPE UUID'.$groupCase);
        $this->addSql('ALTER TABLE car_recommendation ALTER tenant_group_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN car_recommendation.tenant_group_id IS \'(DC2Type:tenant_group_id)\'');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER tenant_group_id TYPE UUID'.$groupCase);
        $this->addSql('ALTER TABLE car_recommendation_part ALTER tenant_group_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN car_recommendation_part.tenant_group_id IS \'(DC2Type:tenant_group_id)\'');
        $this->addSql('ALTER TABLE customer_transaction ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE customer_transaction ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN customer_transaction.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE employee ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE employee ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN employee.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE employee_salary ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE employee_salary ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN employee_salary.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE employee_salary_end ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE employee_salary_end ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN employee_salary_end.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE expense ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE expense ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN expense.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE google_review_token ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE google_review_token ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN google_review_token.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE income ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE income ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN income.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE income_accrue ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE income_accrue ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN income_accrue.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE income_part ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE income_part ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN income_part.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE inventorization ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE inventorization ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN inventorization.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE inventorization_close ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE inventorization_close ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN inventorization_close.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE inventorization_part ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE inventorization_part ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN inventorization_part.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE mc_equipment ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE mc_equipment ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN mc_equipment.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE mc_line ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE mc_line ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN mc_line.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE mc_part ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE mc_part ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN mc_part.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE mc_work ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE mc_work ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN mc_work.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE motion ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE motion ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN motion.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE note ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE note ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN note.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE note_delete ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE note_delete ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN note_delete.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE order_close ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE order_close ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN order_close.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE order_item ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE order_item ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN order_item.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE order_payment ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE order_payment ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN order_payment.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE order_suspend ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE order_suspend ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN order_suspend.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE orders ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE orders ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN orders.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE organization ALTER tenant_group_id TYPE UUID'.$groupCase);
        $this->addSql('ALTER TABLE organization ALTER tenant_group_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN organization.tenant_group_id IS \'(DC2Type:tenant_group_id)\'');
        $this->addSql('ALTER TABLE part_discount ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE part_discount ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN part_discount.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE part_price ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE part_price ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN part_price.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE part_required_availability ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE part_required_availability ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN part_required_availability.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE part_supply ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE part_supply ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN part_supply.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE person ALTER tenant_group_id TYPE UUID'.$groupCase);
        $this->addSql('ALTER TABLE person ALTER tenant_group_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN person.tenant_group_id IS \'(DC2Type:tenant_group_id)\'');
        $this->addSql('ALTER TABLE publish ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE publish ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN publish.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE reservation ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE reservation ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN reservation.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE review ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE review ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN review.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE sms ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE sms ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN sms.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE sms_send ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE sms_send ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN sms_send.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE storage_part ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE storage_part ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN storage_part.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE user_permission ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE user_permission ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN user_permission.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE wallet ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE wallet ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN wallet.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE wallet_transaction ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE wallet_transaction ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN wallet_transaction.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE warehouse ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE warehouse ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN warehouse.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE warehouse_code ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE warehouse_code ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN warehouse_code.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE warehouse_name ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE warehouse_name ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN warehouse_name.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('ALTER TABLE warehouse_parent ALTER tenant_id TYPE UUID'.$tenantCase);
        $this->addSql('ALTER TABLE warehouse_parent ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN warehouse_parent.tenant_id IS \'(DC2Type:tenant_id)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE appeal_calculator ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE appeal_calculator ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_calculator.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE appeal_call ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE appeal_call ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_call.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE appeal_cooperation ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE appeal_cooperation ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_cooperation.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE appeal_postpone ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE appeal_postpone ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_postpone.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE appeal_question ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE appeal_question ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_question.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE appeal_schedule ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE appeal_schedule ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_schedule.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE appeal_status ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE appeal_status ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_status.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE appeal_tire_fitting ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE appeal_tire_fitting ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appeal_tire_fitting.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE created_by ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE created_by ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN created_by.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE calendar_entry_order ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE calendar_entry_order ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN calendar_entry_order.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE calendar_entry_schedule ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE calendar_entry_schedule ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN calendar_entry_schedule.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER tenant_group_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER tenant_group_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN car_recommendation_part.tenant_group_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE calendar_entry_deletion ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE calendar_entry_deletion ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN calendar_entry_deletion.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE calendar_entry ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE calendar_entry ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN calendar_entry.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE car ALTER tenant_group_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE car ALTER tenant_group_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN car.tenant_group_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE car_recommendation ALTER tenant_group_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE car_recommendation ALTER tenant_group_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN car_recommendation.tenant_group_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE customer_transaction ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE customer_transaction ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN customer_transaction.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE wallet_transaction ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE wallet_transaction ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN wallet_transaction.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE organization ALTER tenant_group_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE organization ALTER tenant_group_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN organization.tenant_group_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE person ALTER tenant_group_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE person ALTER tenant_group_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN person.tenant_group_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE employee ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE employee ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN employee.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE expense ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE expense ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN expense.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE google_review_token ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE google_review_token ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN google_review_token.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE inventorization_part ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE inventorization_part ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN inventorization_part.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE income ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE income ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN income.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE reservation ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE reservation ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN reservation.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE inventorization ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE inventorization ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN inventorization.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE inventorization_close ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE inventorization_close ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN inventorization_close.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE employee_salary_end ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE employee_salary_end ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN employee_salary_end.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE income_part ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE income_part ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN income_part.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE motion ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE motion ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN motion.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE mc_work ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE mc_work ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN mc_work.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE order_suspend ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE order_suspend ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN order_suspend.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE mc_line ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE mc_line ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN mc_line.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE order_close ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE order_close ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN order_close.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE part_discount ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE part_discount ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN part_discount.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE part_price ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE part_price ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN part_price.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE part_required_availability ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE part_required_availability ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN part_required_availability.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE part_supply ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE part_supply ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN part_supply.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE mc_part ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE mc_part ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN mc_part.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE order_item ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE order_item ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN order_item.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE orders ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE orders ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN orders.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE order_payment ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE order_payment ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN order_payment.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE mc_equipment ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE mc_equipment ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN mc_equipment.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE publish ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE publish ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN publish.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE review ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE review ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN review.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE sms ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE sms ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN sms.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE sms_send ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE sms_send ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN sms_send.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE user_permission ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE user_permission ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN user_permission.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE wallet ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE wallet ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN wallet.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE warehouse ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE warehouse ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN warehouse.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE warehouse_code ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE warehouse_code ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN warehouse_code.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE warehouse_name ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE warehouse_name ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN warehouse_name.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE warehouse_parent ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE warehouse_parent ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN warehouse_parent.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE note ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE note ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN note.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE note_delete ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE note_delete ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN note_delete.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE income_accrue ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE income_accrue ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN income_accrue.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE employee_salary ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE employee_salary ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN employee_salary.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE calendar_entry_order_info ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE calendar_entry_order_info ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN calendar_entry_order_info.tenant_id IS \'(DC2Type:tenant_enum)\'');
        $this->addSql('ALTER TABLE storage_part ALTER tenant_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE storage_part ALTER tenant_id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN storage_part.tenant_id IS \'(DC2Type:tenant_enum)\'');
    }
}
