<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use function strpos;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200307221417 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf('postgresql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'postgresql\'.');

        $this->skipIf(0 !== strpos($this->connection->getDatabase(), 'landlord'), 'Landlord only');

        $this->addSql('ALTER TABLE part_case ALTER id TYPE INT');
        $this->addSql('ALTER TABLE part_case ALTER part_id TYPE INT');
        $this->addSql('ALTER TABLE part_case ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE part_case ALTER car_model_id TYPE INT');
        $this->addSql('ALTER TABLE part_case ALTER car_model_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16548_idx_2a0e7894ce34bec RENAME TO IDX_2A0E7894CE34BEC');
        $this->addSql('ALTER INDEX idx_16548_idx_2a0e789f64382e3 RENAME TO IDX_2A0E789F64382E3');
        $this->addSql('ALTER INDEX idx_16548_unique_idx RENAME TO UNIQ_2A0E7894CE34BECF64382E3');
        $this->addSql('ALTER TABLE balance ALTER id TYPE INT');
        $this->addSql('ALTER TABLE balance ALTER operand_id TYPE INT');
        $this->addSql('ALTER TABLE balance ALTER operand_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16388_idx_acf41ffe18d7f226 RENAME TO IDX_ACF41FFE18D7F226');
        $this->addSql('ALTER INDEX idx_16388_unique_idx RENAME TO UNIQ_ACF41FFE18D7F2264E59C462');
        $this->addSql('ALTER TABLE person ALTER id TYPE INT');
        $this->addSql('ALTER TABLE person ALTER id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16564_uniq_34dcd176450ff010 RENAME TO UNIQ_34DCD176450FF010');
        $this->addSql('ALTER TABLE operand ALTER id TYPE INT');
        $this->addSql('ALTER TABLE operand ALTER type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE operand ALTER type DROP DEFAULT');
        $this->addSql('ALTER TABLE organization ALTER id TYPE INT');
        $this->addSql('ALTER TABLE organization ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE stockpile ALTER id TYPE INT');
        $this->addSql('ALTER TABLE stockpile ALTER part_id TYPE INT');
        $this->addSql('ALTER TABLE stockpile ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE stockpile ALTER quantity TYPE INT');
        $this->addSql('ALTER TABLE stockpile ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16582_idx_c2e8923f4ce34bec RENAME TO IDX_C2E8923F4CE34BEC');
        $this->addSql('ALTER INDEX idx_16582_search_idx RENAME TO IDX_C2E8923F4CE34BEC4E59C4629FF31636');
        $this->addSql('ALTER INDEX idx_16582_part_tenant_unique_idx RENAME TO UNIQ_C2E8923F4CE34BEC4E59C462');
        $this->addSql('ALTER TABLE operand_note ALTER id TYPE INT');
        $this->addSql('ALTER TABLE operand_note ALTER operand_id TYPE INT');
        $this->addSql('ALTER TABLE operand_note ALTER operand_id DROP DEFAULT');
        $this->addSql('ALTER TABLE operand_note ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE operand_note ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16509_idx_36bde44118d7f226 RENAME TO IDX_36BDE44118D7F226');
        $this->addSql('ALTER INDEX idx_16509_idx_36bde441b03a8386 RENAME TO IDX_36BDE441B03A8386');
        $this->addSql('ALTER TABLE part ALTER id TYPE INT');
        $this->addSql('ALTER TABLE part ALTER manufacturer_id TYPE INT');
        $this->addSql('ALTER TABLE part ALTER manufacturer_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16535_idx_490f70c6a23b42d RENAME TO IDX_490F70C6A23B42D');
        $this->addSql('ALTER INDEX idx_16535_part_idx RENAME TO UNIQ_490F70C696901F54A23B42D');
        $this->addSql('ALTER TABLE part_part ALTER part_source TYPE INT');
        $this->addSql('ALTER TABLE part_part ALTER part_source DROP DEFAULT');
        $this->addSql('ALTER TABLE part_part ALTER part_target TYPE INT');
        $this->addSql('ALTER TABLE part_part ALTER part_target DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16561_idx_33a70e4b661abfe6 RENAME TO IDX_33A70E4B661ABFE6');
        $this->addSql('ALTER INDEX idx_16561_idx_33a70e4b7fffef69 RENAME TO IDX_33A70E4B7FFFEF69');
        $this->addSql('ALTER TABLE event ALTER id TYPE INT');
        $this->addSql('ALTER TABLE event ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE event ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16447_idx_3bae0aa7b03a8386 RENAME TO IDX_3BAE0AA7B03A8386');
        $this->addSql('ALTER TABLE part_cross ALTER id TYPE INT');
        $this->addSql('ALTER TABLE part_cross_part ALTER part_cross_id TYPE INT');
        $this->addSql('ALTER TABLE part_cross_part ALTER part_cross_id DROP DEFAULT');
        $this->addSql('ALTER TABLE part_cross_part ALTER part_id TYPE INT');
        $this->addSql('ALTER TABLE part_cross_part ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16558_idx_b98f499c70b9088c RENAME TO IDX_B98F499C70B9088C');
        $this->addSql('ALTER INDEX idx_16558_uniq_b98f499c4ce34bec RENAME TO UNIQ_B98F499C4CE34BEC');
        $this->addSql('ALTER TABLE mc_work ALTER id TYPE INT');
        $this->addSql('ALTER TABLE mc_part ALTER id TYPE INT');
        $this->addSql('ALTER TABLE mc_part ALTER line_id TYPE INT');
        $this->addSql('ALTER TABLE mc_part ALTER line_id DROP DEFAULT');
        $this->addSql('ALTER TABLE mc_part ALTER part_id TYPE INT');
        $this->addSql('ALTER TABLE mc_part ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE mc_part ALTER quantity TYPE INT');
        $this->addSql('ALTER TABLE mc_part ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16481_idx_2b65786f4d7b7542 RENAME TO IDX_2B65786F4D7B7542');
        $this->addSql('ALTER INDEX idx_16481_idx_2b65786f4ce34bec RENAME TO IDX_2B65786F4CE34BEC');
        $this->addSql('ALTER TABLE mc_line ALTER id TYPE INT');
        $this->addSql('ALTER TABLE mc_line ALTER equipment_id TYPE INT');
        $this->addSql('ALTER TABLE mc_line ALTER equipment_id DROP DEFAULT');
        $this->addSql('ALTER TABLE mc_line ALTER work_id TYPE INT');
        $this->addSql('ALTER TABLE mc_line ALTER work_id DROP DEFAULT');
        $this->addSql('ALTER TABLE mc_line ALTER period TYPE INT');
        $this->addSql('ALTER TABLE mc_line ALTER period DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16475_idx_b37ebc5f517fe9fe RENAME TO IDX_B37EBC5F517FE9FE');
        $this->addSql('ALTER INDEX idx_16475_idx_b37ebc5fbb3453db RENAME TO IDX_B37EBC5FBB3453DB');
        $this->addSql('ALTER TABLE mc_equipment ALTER id TYPE INT');
        $this->addSql('ALTER TABLE mc_equipment ALTER model_id TYPE INT');
        $this->addSql('ALTER TABLE mc_equipment ALTER model_id DROP DEFAULT');
        $this->addSql('ALTER TABLE mc_equipment ALTER period TYPE INT');
        $this->addSql('ALTER TABLE mc_equipment ALTER period DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16465_idx_793047587975b7e7 RENAME TO IDX_793047587975B7E7');
        $this->addSql('ALTER TABLE review ALTER id TYPE INT');
        $this->addSql('ALTER TABLE car_note ALTER id TYPE INT');
        $this->addSql('ALTER TABLE car_note ALTER car_id TYPE INT');
        $this->addSql('ALTER TABLE car_note ALTER car_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_note ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE car_note ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16419_idx_4d7eeb8c3c6f69f RENAME TO IDX_4D7EEB8C3C6F69F');
        $this->addSql('ALTER INDEX idx_16419_idx_4d7eeb8b03a8386 RENAME TO IDX_4D7EEB8B03A8386');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER id TYPE INT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER recommendation_id TYPE INT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER recommendation_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER part_id TYPE INT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER quantity TYPE INT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16439_idx_ddc72d65d173940b RENAME TO IDX_DDC72D65D173940B');
        $this->addSql('ALTER INDEX idx_16439_idx_ddc72d654ce34bec RENAME TO IDX_DDC72D654CE34BEC');
        $this->addSql('ALTER INDEX idx_16439_idx_ddc72d65b03a8386 RENAME TO IDX_DDC72D65B03A8386');
        $this->addSql('ALTER TABLE car ALTER id TYPE INT');
        $this->addSql('ALTER TABLE car ALTER model_id TYPE INT');
        $this->addSql('ALTER TABLE car ALTER model_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car ALTER owner_id TYPE INT');
        $this->addSql('ALTER TABLE car ALTER owner_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car ALTER year TYPE INT');
        $this->addSql('ALTER TABLE car ALTER year DROP DEFAULT');
        $this->addSql('ALTER TABLE car ALTER mileage TYPE INT');
        $this->addSql('ALTER TABLE car ALTER mileage DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16396_uniq_773de69d772e836a RENAME TO UNIQ_773DE69D772E836A');
        $this->addSql('ALTER INDEX idx_16396_idx_773de69d7975b7e7 RENAME TO IDX_773DE69D7975B7E7');
        $this->addSql('ALTER INDEX idx_16396_idx_773de69d7e3c61f9 RENAME TO IDX_773DE69D7E3C61F9');
        $this->addSql('ALTER TABLE car_recommendation ALTER id TYPE INT');
        $this->addSql('ALTER TABLE car_recommendation ALTER car_id TYPE INT');
        $this->addSql('ALTER TABLE car_recommendation ALTER car_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation ALTER worker_id TYPE INT');
        $this->addSql('ALTER TABLE car_recommendation ALTER worker_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE car_recommendation ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation ALTER expired_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE car_recommendation ALTER expired_at DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation ALTER realization_id TYPE INT');
        $this->addSql('ALTER TABLE car_recommendation ALTER realization_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16428_idx_8e4baaf2c3c6f69f RENAME TO IDX_8E4BAAF2C3C6F69F');
        $this->addSql('ALTER INDEX idx_16428_idx_8e4baaf26b20ba36 RENAME TO IDX_8E4BAAF26B20BA36');
        $this->addSql('ALTER INDEX idx_16428_idx_8e4baaf2b03a8386 RENAME TO IDX_8E4BAAF2B03A8386');
        $this->addSql('ALTER TABLE car_model ALTER id TYPE INT');
        $this->addSql('ALTER TABLE car_model ALTER manufacturer_id TYPE INT');
        $this->addSql('ALTER TABLE car_model ALTER manufacturer_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16408_idx_83ef70ea23b42d RENAME TO IDX_83EF70EA23B42D');
        $this->addSql('ALTER INDEX idx_16408_manufacturer_case_idx RENAME TO UNIQ_83EF70EA23B42DDF3BA4B5');
        $this->addSql('ALTER TABLE manufacturer ALTER id TYPE INT');
        $this->addSql('ALTER TABLE user_credentials ALTER id TYPE INT');
        $this->addSql('ALTER TABLE user_credentials ALTER user_id TYPE INT');
        $this->addSql('ALTER TABLE user_credentials ALTER user_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16597_idx_531ee19ba76ed395 RENAME TO IDX_531EE19BA76ED395');
        $this->addSql('ALTER TABLE users ALTER id TYPE INT');
        $this->addSql('ALTER TABLE users ALTER person_id TYPE INT');
        $this->addSql('ALTER TABLE users ALTER person_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16588_uniq_1483a5e9f85e0677 RENAME TO UNIQ_1483A5E9F85E0677');
        $this->addSql('ALTER INDEX idx_16588_uniq_1483a5e9217bbb47 RENAME TO UNIQ_1483A5E9217BBB47');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf('postgresql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE car_note ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_note ALTER car_id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_note ALTER car_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_note ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_note ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_4d7eeb8c3c6f69f RENAME TO idx_16419_idx_4d7eeb8c3c6f69f');
        $this->addSql('ALTER INDEX idx_4d7eeb8b03a8386 RENAME TO idx_16419_idx_4d7eeb8b03a8386');
        $this->addSql('ALTER TABLE balance ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE balance ALTER operand_id TYPE BIGINT');
        $this->addSql('ALTER TABLE balance ALTER operand_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_acf41ffe18d7f226 RENAME TO idx_16388_idx_acf41ffe18d7f226');
        $this->addSql('ALTER INDEX uniq_acf41ffe18d7f2264e59c462 RENAME TO idx_16388_unique_idx');
        $this->addSql('ALTER TABLE car_model ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_model ALTER manufacturer_id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_model ALTER manufacturer_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_83ef70ea23b42d RENAME TO idx_16408_idx_83ef70ea23b42d');
        $this->addSql('ALTER INDEX uniq_83ef70ea23b42ddf3ba4b5 RENAME TO idx_16408_manufacturer_case_idx');
        $this->addSql('ALTER TABLE manufacturer ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER recommendation_id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER recommendation_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER part_id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER quantity TYPE BIGINT');
        $this->addSql('ALTER TABLE car_recommendation_part ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_ddc72d65d173940b RENAME TO idx_16439_idx_ddc72d65d173940b');
        $this->addSql('ALTER INDEX idx_ddc72d654ce34bec RENAME TO idx_16439_idx_ddc72d654ce34bec');
        $this->addSql('ALTER INDEX idx_ddc72d65b03a8386 RENAME TO idx_16439_idx_ddc72d65b03a8386');
        $this->addSql('ALTER TABLE car_recommendation ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_recommendation ALTER car_id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_recommendation ALTER car_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation ALTER worker_id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_recommendation ALTER worker_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_recommendation ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation ALTER expired_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE car_recommendation ALTER expired_at DROP DEFAULT');
        $this->addSql('ALTER TABLE car_recommendation ALTER realization_id TYPE BIGINT');
        $this->addSql('ALTER TABLE car_recommendation ALTER realization_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_8e4baaf2c3c6f69f RENAME TO idx_16428_idx_8e4baaf2c3c6f69f');
        $this->addSql('ALTER INDEX idx_8e4baaf26b20ba36 RENAME TO idx_16428_idx_8e4baaf26b20ba36');
        $this->addSql('ALTER INDEX idx_8e4baaf2b03a8386 RENAME TO idx_16428_idx_8e4baaf2b03a8386');
        $this->addSql('ALTER TABLE event ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE event ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE event ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_3bae0aa7b03a8386 RENAME TO idx_16447_idx_3bae0aa7b03a8386');
        $this->addSql('ALTER TABLE mc_equipment ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE mc_equipment ALTER model_id TYPE BIGINT');
        $this->addSql('ALTER TABLE mc_equipment ALTER model_id DROP DEFAULT');
        $this->addSql('ALTER TABLE mc_equipment ALTER period TYPE BIGINT');
        $this->addSql('ALTER TABLE mc_equipment ALTER period DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_793047587975b7e7 RENAME TO idx_16465_idx_793047587975b7e7');
        $this->addSql('ALTER TABLE part_cross_part ALTER part_cross_id TYPE BIGINT');
        $this->addSql('ALTER TABLE part_cross_part ALTER part_cross_id DROP DEFAULT');
        $this->addSql('ALTER TABLE part_cross_part ALTER part_id TYPE BIGINT');
        $this->addSql('ALTER TABLE part_cross_part ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_b98f499c70b9088c RENAME TO idx_16558_idx_b98f499c70b9088c');
        $this->addSql('ALTER INDEX uniq_b98f499c4ce34bec RENAME TO idx_16558_uniq_b98f499c4ce34bec');
        $this->addSql('ALTER TABLE user_credentials ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE user_credentials ALTER user_id TYPE BIGINT');
        $this->addSql('ALTER TABLE user_credentials ALTER user_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_531ee19ba76ed395 RENAME TO idx_16597_idx_531ee19ba76ed395');
        $this->addSql('ALTER TABLE stockpile ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE stockpile ALTER part_id TYPE BIGINT');
        $this->addSql('ALTER TABLE stockpile ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE stockpile ALTER quantity TYPE BIGINT');
        $this->addSql('ALTER TABLE stockpile ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_c2e8923f4ce34bec RENAME TO idx_16582_idx_c2e8923f4ce34bec');
        $this->addSql('ALTER INDEX idx_c2e8923f4ce34bec4e59c4629ff31636 RENAME TO idx_16582_search_idx');
        $this->addSql('ALTER INDEX uniq_c2e8923f4ce34bec4e59c462 RENAME TO idx_16582_part_tenant_unique_idx');
        $this->addSql('ALTER TABLE mc_part ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE mc_part ALTER line_id TYPE BIGINT');
        $this->addSql('ALTER TABLE mc_part ALTER line_id DROP DEFAULT');
        $this->addSql('ALTER TABLE mc_part ALTER part_id TYPE BIGINT');
        $this->addSql('ALTER TABLE mc_part ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE mc_part ALTER quantity TYPE BIGINT');
        $this->addSql('ALTER TABLE mc_part ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_2b65786f4ce34bec RENAME TO idx_16481_idx_2b65786f4ce34bec');
        $this->addSql('ALTER INDEX idx_2b65786f4d7b7542 RENAME TO idx_16481_idx_2b65786f4d7b7542');
        $this->addSql('ALTER TABLE review ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE mc_work ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE person ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE person ALTER id DROP DEFAULT');
        $this->addSql('ALTER INDEX uniq_34dcd176450ff010 RENAME TO idx_16564_uniq_34dcd176450ff010');
        $this->addSql('ALTER TABLE part ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE part ALTER manufacturer_id TYPE BIGINT');
        $this->addSql('ALTER TABLE part ALTER manufacturer_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_490f70c6a23b42d RENAME TO idx_16535_idx_490f70c6a23b42d');
        $this->addSql('ALTER INDEX uniq_490f70c696901f54a23b42d RENAME TO idx_16535_part_idx');
        $this->addSql('ALTER TABLE part_part ALTER part_source TYPE BIGINT');
        $this->addSql('ALTER TABLE part_part ALTER part_source DROP DEFAULT');
        $this->addSql('ALTER TABLE part_part ALTER part_target TYPE BIGINT');
        $this->addSql('ALTER TABLE part_part ALTER part_target DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_33a70e4b661abfe6 RENAME TO idx_16561_idx_33a70e4b661abfe6');
        $this->addSql('ALTER INDEX idx_33a70e4b7fffef69 RENAME TO idx_16561_idx_33a70e4b7fffef69');
        $this->addSql('ALTER TABLE operand ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE operand ALTER type TYPE BIGINT');
        $this->addSql('ALTER TABLE operand ALTER type DROP DEFAULT');
        $this->addSql('ALTER TABLE operand_note ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE operand_note ALTER operand_id TYPE BIGINT');
        $this->addSql('ALTER TABLE operand_note ALTER operand_id DROP DEFAULT');
        $this->addSql('ALTER TABLE operand_note ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE operand_note ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_36bde441b03a8386 RENAME TO idx_16509_idx_36bde441b03a8386');
        $this->addSql('ALTER INDEX idx_36bde44118d7f226 RENAME TO idx_16509_idx_36bde44118d7f226');
        $this->addSql('ALTER TABLE part_cross ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE organization ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE organization ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE users ALTER person_id TYPE BIGINT');
        $this->addSql('ALTER TABLE users ALTER person_id DROP DEFAULT');
        $this->addSql('ALTER INDEX uniq_1483a5e9f85e0677 RENAME TO idx_16588_uniq_1483a5e9f85e0677');
        $this->addSql('ALTER INDEX uniq_1483a5e9217bbb47 RENAME TO idx_16588_uniq_1483a5e9217bbb47');
        $this->addSql('ALTER TABLE part_case ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE part_case ALTER part_id TYPE BIGINT');
        $this->addSql('ALTER TABLE part_case ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE part_case ALTER car_model_id TYPE BIGINT');
        $this->addSql('ALTER TABLE part_case ALTER car_model_id DROP DEFAULT');
        $this->addSql('ALTER INDEX uniq_2a0e7894ce34becf64382e3 RENAME TO idx_16548_unique_idx');
        $this->addSql('ALTER INDEX idx_2a0e789f64382e3 RENAME TO idx_16548_idx_2a0e789f64382e3');
        $this->addSql('ALTER INDEX idx_2a0e7894ce34bec RENAME TO idx_16548_idx_2a0e7894ce34bec');
        $this->addSql('ALTER TABLE mc_line ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE mc_line ALTER equipment_id TYPE BIGINT');
        $this->addSql('ALTER TABLE mc_line ALTER equipment_id DROP DEFAULT');
        $this->addSql('ALTER TABLE mc_line ALTER work_id TYPE BIGINT');
        $this->addSql('ALTER TABLE mc_line ALTER work_id DROP DEFAULT');
        $this->addSql('ALTER TABLE mc_line ALTER period TYPE BIGINT');
        $this->addSql('ALTER TABLE mc_line ALTER period DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_b37ebc5f517fe9fe RENAME TO idx_16475_idx_b37ebc5f517fe9fe');
        $this->addSql('ALTER INDEX idx_b37ebc5fbb3453db RENAME TO idx_16475_idx_b37ebc5fbb3453db');
        $this->addSql('ALTER TABLE car ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE car ALTER model_id TYPE BIGINT');
        $this->addSql('ALTER TABLE car ALTER model_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car ALTER owner_id TYPE BIGINT');
        $this->addSql('ALTER TABLE car ALTER owner_id DROP DEFAULT');
        $this->addSql('ALTER TABLE car ALTER year TYPE BIGINT');
        $this->addSql('ALTER TABLE car ALTER year DROP DEFAULT');
        $this->addSql('ALTER TABLE car ALTER mileage TYPE BIGINT');
        $this->addSql('ALTER TABLE car ALTER mileage DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_773de69d7e3c61f9 RENAME TO idx_16396_idx_773de69d7e3c61f9');
        $this->addSql('ALTER INDEX uniq_773de69d772e836a RENAME TO idx_16396_uniq_773de69d772e836a');
        $this->addSql('ALTER INDEX idx_773de69d7975b7e7 RENAME TO idx_16396_idx_773de69d7975b7e7');
    }
}
