<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use function strpos;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200307221419 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf('postgresql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'postgresql\'.');

        $this->skipIf(0 !== strpos($this->connection->getDatabase(), 'tenant'), 'Tenant only');

        $this->addSql('ALTER TABLE orders ALTER id TYPE INT');
        $this->addSql('ALTER TABLE orders ALTER worker_id TYPE INT');
        $this->addSql('ALTER TABLE orders ALTER worker_id DROP DEFAULT');
        $this->addSql('ALTER TABLE orders ALTER closed_by_id TYPE INT');
        $this->addSql('ALTER TABLE orders ALTER closed_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE orders ALTER car_id TYPE INT');
        $this->addSql('ALTER TABLE orders ALTER car_id DROP DEFAULT');
        $this->addSql('ALTER TABLE orders ALTER customer_id TYPE INT');
        $this->addSql('ALTER TABLE orders ALTER customer_id DROP DEFAULT');
        $this->addSql('ALTER TABLE orders ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE orders ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16481_idx_e52ffdee6b20ba36 RENAME TO IDX_E52FFDEE6B20BA36');
        $this->addSql('ALTER INDEX idx_16481_search_idx RENAME TO IDX_E52FFDEE5D13417F');
        $this->addSql('ALTER TABLE motion_old ALTER id TYPE INT');
        $this->addSql('ALTER TABLE motion_old ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE motion ALTER id TYPE INT');
        $this->addSql('ALTER TABLE motion ALTER quantity TYPE INT');
        $this->addSql('ALTER TABLE motion ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE motion ALTER type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE motion ALTER type DROP DEFAULT');
        $this->addSql('ALTER TABLE motion ALTER part_id TYPE INT');
        $this->addSql('ALTER TABLE motion ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16449_part_idx RENAME TO IDX_F5FEA1E84CE34BEC');
        $this->addSql('ALTER TABLE order_payment ALTER id TYPE INT');
        $this->addSql('ALTER TABLE order_payment ALTER order_id TYPE INT');
        $this->addSql('ALTER TABLE order_payment ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_payment ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE order_payment ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16538_idx_9b522d468d9f6d38 RENAME TO IDX_9B522D468D9F6D38');
        $this->addSql('ALTER TABLE motion_manual ALTER id TYPE INT');
        $this->addSql('ALTER TABLE motion_manual ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE motion_manual ALTER user_id TYPE INT');
        $this->addSql('ALTER TABLE motion_manual ALTER user_id DROP DEFAULT');
        $this->addSql('ALTER TABLE penalty ALTER id TYPE INT');
        $this->addSql('ALTER TABLE penalty ALTER transaction_id TYPE INT');
        $this->addSql('ALTER TABLE penalty ALTER transaction_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16562_idx_afe28fd82fc0cb0f RENAME TO IDX_AFE28FD82FC0CB0F');
        $this->addSql('ALTER TABLE reservation ALTER id TYPE INT');
        $this->addSql('ALTER TABLE reservation ALTER order_item_part_id TYPE INT');
        $this->addSql('ALTER TABLE reservation ALTER order_item_part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE reservation ALTER quantity TYPE INT');
        $this->addSql('ALTER TABLE reservation ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16568_idx_42c84955437ef9d2 RENAME TO IDX_42C84955437EF9D2');
        $this->addSql('ALTER TABLE order_item ALTER id TYPE INT');
        $this->addSql('ALTER TABLE order_item ALTER order_id TYPE INT');
        $this->addSql('ALTER TABLE order_item ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER parent_id TYPE INT');
        $this->addSql('ALTER TABLE order_item ALTER parent_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE order_item ALTER type DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE order_item ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16500_idx_52ea1f098d9f6d38 RENAME TO IDX_52EA1F098D9F6D38');
        $this->addSql('ALTER INDEX idx_16500_idx_52ea1f09727aca70 RENAME TO IDX_52EA1F09727ACA70');
        $this->addSql('ALTER TABLE order_item_part ALTER id TYPE INT');
        $this->addSql('ALTER TABLE order_item_part ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item_part ALTER quantity TYPE INT');
        $this->addSql('ALTER TABLE order_item_part ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item_part ALTER part_id TYPE INT');
        $this->addSql('ALTER TABLE order_item_part ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item_part ALTER supplier_id TYPE INT');
        $this->addSql('ALTER TABLE order_item_part ALTER supplier_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_contractor ALTER id TYPE INT');
        $this->addSql('ALTER TABLE order_contractor ALTER order_id TYPE INT');
        $this->addSql('ALTER TABLE order_contractor ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_contractor ALTER contractor_id TYPE INT');
        $this->addSql('ALTER TABLE order_contractor ALTER contractor_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16492_idx_f0a12fba8d9f6d38 RENAME TO IDX_F0A12FBA8D9F6D38');
        $this->addSql('ALTER TABLE income ALTER id TYPE INT');
        $this->addSql('ALTER TABLE income ALTER supplier_id TYPE INT');
        $this->addSql('ALTER TABLE income ALTER supplier_id DROP DEFAULT');
        $this->addSql('ALTER TABLE income ALTER accrued_by_id TYPE INT');
        $this->addSql('ALTER TABLE income ALTER accrued_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE income ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE income ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16418_search_idx RENAME TO IDX_3FA862D06FC55E56');
        $this->addSql('ALTER TABLE order_suspend ALTER id TYPE INT');
        $this->addSql('ALTER TABLE order_suspend ALTER order_id TYPE INT');
        $this->addSql('ALTER TABLE order_suspend ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_suspend ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE order_suspend ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16556_idx_c789f0d18d9f6d38 RENAME TO IDX_C789F0D18D9F6D38');
        $this->addSql('ALTER TABLE expense ALTER id TYPE INT');
        $this->addSql('ALTER TABLE expense ALTER wallet_id TYPE INT');
        $this->addSql('ALTER TABLE expense ALTER wallet_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16400_idx_2d3a8da6712520f3 RENAME TO IDX_2D3A8DA6712520F3');
        $this->addSql('ALTER TABLE employee ALTER id TYPE INT');
        $this->addSql('ALTER TABLE employee ALTER ratio TYPE INT');
        $this->addSql('ALTER TABLE employee ALTER ratio DROP DEFAULT');
        $this->addSql('ALTER TABLE employee ALTER hired_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE employee ALTER hired_at DROP DEFAULT');
        $this->addSql('ALTER TABLE employee ALTER fired_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE employee ALTER fired_at DROP DEFAULT');
        $this->addSql('ALTER TABLE employee ALTER person_id TYPE INT');
        $this->addSql('ALTER TABLE employee ALTER person_id DROP DEFAULT');
        $this->addSql('ALTER TABLE wallet_transaction ALTER id TYPE INT');
        $this->addSql('ALTER TABLE wallet_transaction ALTER recipient_id TYPE INT');
        $this->addSql('ALTER TABLE wallet_transaction ALTER recipient_id DROP DEFAULT');
        $this->addSql('ALTER TABLE wallet_transaction ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE wallet_transaction ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16588_idx_7daf972e92f8f78 RENAME TO IDX_7DAF972E92F8F78');
        $this->addSql('ALTER TABLE expense_item ALTER id TYPE INT');
        $this->addSql('ALTER TABLE expense_item ALTER expense_id TYPE INT');
        $this->addSql('ALTER TABLE expense_item ALTER expense_id DROP DEFAULT');
        $this->addSql('ALTER TABLE expense_item ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE expense_item ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16406_idx_abbc6b7cf395db7b RENAME TO IDX_ABBC6B7CF395DB7B');
        $this->addSql('ALTER TABLE monthly_salary ALTER id TYPE INT');
        $this->addSql('ALTER TABLE monthly_salary ALTER employee_id TYPE INT');
        $this->addSql('ALTER TABLE monthly_salary ALTER employee_id DROP DEFAULT');
        $this->addSql('ALTER TABLE monthly_salary ALTER payday TYPE INT');
        $this->addSql('ALTER TABLE monthly_salary ALTER payday DROP DEFAULT');
        $this->addSql('ALTER TABLE monthly_salary ALTER ended_by_id TYPE INT');
        $this->addSql('ALTER TABLE monthly_salary ALTER ended_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE monthly_salary ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE monthly_salary ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16441_idx_77b328ba8c03f15c RENAME TO IDX_77B328BA8C03F15C');
        $this->addSql('ALTER TABLE order_item_service ALTER id TYPE INT');
        $this->addSql('ALTER TABLE order_item_service ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item_service ALTER worker_id TYPE INT');
        $this->addSql('ALTER TABLE order_item_service ALTER worker_id DROP DEFAULT');
        $this->addSql('ALTER TABLE salary ALTER id TYPE INT');
        $this->addSql('ALTER TABLE salary ALTER income_id TYPE INT');
        $this->addSql('ALTER TABLE salary ALTER income_id DROP DEFAULT');
        $this->addSql('ALTER TABLE salary ALTER outcome_id TYPE INT');
        $this->addSql('ALTER TABLE salary ALTER outcome_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16574_idx_9413bb71640ed2c0 RENAME TO IDX_9413BB71640ED2C0');
        $this->addSql('ALTER INDEX idx_16574_idx_9413bb71e6ee6d63 RENAME TO IDX_9413BB71E6EE6D63');
        $this->addSql('ALTER TABLE motion_income ALTER id TYPE INT');
        $this->addSql('ALTER TABLE motion_income ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE motion_income ALTER income_part_id TYPE INT');
        $this->addSql('ALTER TABLE motion_income ALTER income_part_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16456_idx_6228a7c1f4a13d95 RENAME TO IDX_6228A7C1F4A13D95');
        $this->addSql('ALTER TABLE motion_order ALTER id TYPE INT');
        $this->addSql('ALTER TABLE motion_order ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE motion_order ALTER order_id TYPE INT');
        $this->addSql('ALTER TABLE motion_order ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16465_idx_1df780628d9f6d38 RENAME TO IDX_1DF780628D9F6D38');
        $this->addSql('ALTER TABLE wallet ALTER id TYPE INT');
        $this->addSql('ALTER TABLE operand_transaction ALTER id TYPE INT');
        $this->addSql('ALTER TABLE operand_transaction ALTER recipient_id TYPE INT');
        $this->addSql('ALTER TABLE operand_transaction ALTER recipient_id DROP DEFAULT');
        $this->addSql('ALTER TABLE operand_transaction ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE operand_transaction ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_note ALTER id TYPE INT');
        $this->addSql('ALTER TABLE order_note ALTER order_id TYPE INT');
        $this->addSql('ALTER TABLE order_note ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_note ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE order_note ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16529_idx_824cc0038d9f6d38 RENAME TO IDX_824CC0038D9F6D38');
        $this->addSql('ALTER TABLE income_part ALTER id TYPE INT');
        $this->addSql('ALTER TABLE income_part ALTER income_id TYPE INT');
        $this->addSql('ALTER TABLE income_part ALTER income_id DROP DEFAULT');
        $this->addSql('ALTER TABLE income_part ALTER accrued_motion_id TYPE INT');
        $this->addSql('ALTER TABLE income_part ALTER accrued_motion_id DROP DEFAULT');
        $this->addSql('ALTER TABLE income_part ALTER quantity TYPE INT');
        $this->addSql('ALTER TABLE income_part ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE income_part ALTER part_id TYPE INT');
        $this->addSql('ALTER TABLE income_part ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16430_idx_834566e8640ed2c0 RENAME TO IDX_834566E8640ED2C0');
        $this->addSql('ALTER INDEX idx_16430_idx_834566e8ffe2c7 RENAME TO IDX_834566E8FFE2C7');
        $this->addSql('ALTER TABLE order_salary ALTER id TYPE INT');
        $this->addSql('ALTER TABLE order_salary ALTER order_id TYPE INT');
        $this->addSql('ALTER TABLE order_salary ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_salary ALTER transaction_id TYPE INT');
        $this->addSql('ALTER TABLE order_salary ALTER transaction_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16550_idx_579caba48d9f6d38 RENAME TO IDX_579CABA48D9F6D38');
        $this->addSql('ALTER INDEX idx_16550_idx_579caba42fc0cb0f RENAME TO IDX_579CABA42FC0CB0F');
        $this->addSql('ALTER TABLE order_item_group ALTER id TYPE INT');
        $this->addSql('ALTER TABLE order_item_group ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE appointment ALTER id TYPE INT');
        $this->addSql('ALTER TABLE appointment ALTER order_id TYPE INT');
        $this->addSql('ALTER TABLE appointment ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE appointment ALTER created_by_id TYPE INT');
        $this->addSql('ALTER TABLE appointment ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_16388_idx_fe38f8448d9f6d38 RENAME TO IDX_FE38F8448D9F6D38');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf('postgresql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE orders ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE orders ALTER worker_id TYPE BIGINT');
        $this->addSql('ALTER TABLE orders ALTER worker_id DROP DEFAULT');
        $this->addSql('ALTER TABLE orders ALTER closed_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE orders ALTER closed_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE orders ALTER car_id TYPE BIGINT');
        $this->addSql('ALTER TABLE orders ALTER car_id DROP DEFAULT');
        $this->addSql('ALTER TABLE orders ALTER customer_id TYPE BIGINT');
        $this->addSql('ALTER TABLE orders ALTER customer_id DROP DEFAULT');
        $this->addSql('ALTER TABLE orders ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE orders ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_e52ffdee5d13417f RENAME TO idx_16481_search_idx');
        $this->addSql('ALTER INDEX idx_e52ffdee6b20ba36 RENAME TO idx_16481_idx_e52ffdee6b20ba36');
        $this->addSql('ALTER TABLE motion_order ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE motion_order ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE motion_order ALTER order_id TYPE BIGINT');
        $this->addSql('ALTER TABLE motion_order ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_1df780628d9f6d38 RENAME TO idx_16465_idx_1df780628d9f6d38');
        $this->addSql('ALTER TABLE expense ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE expense ALTER wallet_id TYPE BIGINT');
        $this->addSql('ALTER TABLE expense ALTER wallet_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_2d3a8da6712520f3 RENAME TO idx_16400_idx_2d3a8da6712520f3');
        $this->addSql('ALTER TABLE order_item_part ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_item_part ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item_part ALTER quantity TYPE BIGINT');
        $this->addSql('ALTER TABLE order_item_part ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item_part ALTER supplier_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_item_part ALTER supplier_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item_part ALTER part_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_item_part ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE monthly_salary ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE monthly_salary ALTER employee_id TYPE BIGINT');
        $this->addSql('ALTER TABLE monthly_salary ALTER employee_id DROP DEFAULT');
        $this->addSql('ALTER TABLE monthly_salary ALTER payday TYPE BIGINT');
        $this->addSql('ALTER TABLE monthly_salary ALTER payday DROP DEFAULT');
        $this->addSql('ALTER TABLE monthly_salary ALTER ended_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE monthly_salary ALTER ended_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE monthly_salary ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE monthly_salary ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_77b328ba8c03f15c RENAME TO idx_16441_idx_77b328ba8c03f15c');
        $this->addSql('ALTER TABLE appointment ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE appointment ALTER order_id TYPE BIGINT');
        $this->addSql('ALTER TABLE appointment ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE appointment ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE appointment ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_fe38f8448d9f6d38 RENAME TO idx_16388_idx_fe38f8448d9f6d38');
        $this->addSql('ALTER TABLE expense_item ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE expense_item ALTER expense_id TYPE BIGINT');
        $this->addSql('ALTER TABLE expense_item ALTER expense_id DROP DEFAULT');
        $this->addSql('ALTER TABLE expense_item ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE expense_item ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_abbc6b7cf395db7b RENAME TO idx_16406_idx_abbc6b7cf395db7b');
        $this->addSql('ALTER TABLE income_part ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE income_part ALTER income_id TYPE BIGINT');
        $this->addSql('ALTER TABLE income_part ALTER income_id DROP DEFAULT');
        $this->addSql('ALTER TABLE income_part ALTER accrued_motion_id TYPE BIGINT');
        $this->addSql('ALTER TABLE income_part ALTER accrued_motion_id DROP DEFAULT');
        $this->addSql('ALTER TABLE income_part ALTER quantity TYPE BIGINT');
        $this->addSql('ALTER TABLE income_part ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE income_part ALTER part_id TYPE BIGINT');
        $this->addSql('ALTER TABLE income_part ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_834566e8ffe2c7 RENAME TO idx_16430_idx_834566e8ffe2c7');
        $this->addSql('ALTER INDEX idx_834566e8640ed2c0 RENAME TO idx_16430_idx_834566e8640ed2c0');
        $this->addSql('ALTER TABLE employee ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE employee ALTER ratio TYPE BIGINT');
        $this->addSql('ALTER TABLE employee ALTER ratio DROP DEFAULT');
        $this->addSql('ALTER TABLE employee ALTER hired_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE employee ALTER hired_at DROP DEFAULT');
        $this->addSql('ALTER TABLE employee ALTER fired_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE employee ALTER fired_at DROP DEFAULT');
        $this->addSql('ALTER TABLE employee ALTER person_id TYPE BIGINT');
        $this->addSql('ALTER TABLE employee ALTER person_id DROP DEFAULT');
        $this->addSql('ALTER TABLE income ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE income ALTER supplier_id TYPE BIGINT');
        $this->addSql('ALTER TABLE income ALTER supplier_id DROP DEFAULT');
        $this->addSql('ALTER TABLE income ALTER accrued_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE income ALTER accrued_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE income ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE income ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_3fa862d06fc55e56 RENAME TO idx_16418_search_idx');
        $this->addSql('ALTER TABLE motion_manual ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE motion_manual ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE motion_manual ALTER user_id TYPE BIGINT');
        $this->addSql('ALTER TABLE motion_manual ALTER user_id DROP DEFAULT');
        $this->addSql('ALTER TABLE motion_income ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE motion_income ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE motion_income ALTER income_part_id TYPE BIGINT');
        $this->addSql('ALTER TABLE motion_income ALTER income_part_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_6228a7c1f4a13d95 RENAME TO idx_16456_idx_6228a7c1f4a13d95');
        $this->addSql('ALTER TABLE motion ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE motion ALTER quantity TYPE BIGINT');
        $this->addSql('ALTER TABLE motion ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE motion ALTER part_id TYPE BIGINT');
        $this->addSql('ALTER TABLE motion ALTER part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE motion ALTER type TYPE BIGINT');
        $this->addSql('ALTER TABLE motion ALTER type DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_f5fea1e84ce34bec RENAME TO idx_16449_part_idx');
        $this->addSql('ALTER TABLE operand_transaction ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE operand_transaction ALTER recipient_id TYPE BIGINT');
        $this->addSql('ALTER TABLE operand_transaction ALTER recipient_id DROP DEFAULT');
        $this->addSql('ALTER TABLE operand_transaction ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE operand_transaction ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_contractor ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_contractor ALTER order_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_contractor ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_contractor ALTER contractor_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_contractor ALTER contractor_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_f0a12fba8d9f6d38 RENAME TO idx_16492_idx_f0a12fba8d9f6d38');
        $this->addSql('ALTER TABLE motion_old ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE motion_old ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE reservation ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE reservation ALTER order_item_part_id TYPE BIGINT');
        $this->addSql('ALTER TABLE reservation ALTER order_item_part_id DROP DEFAULT');
        $this->addSql('ALTER TABLE reservation ALTER quantity TYPE BIGINT');
        $this->addSql('ALTER TABLE reservation ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_42c84955437ef9d2 RENAME TO idx_16568_idx_42c84955437ef9d2');
        $this->addSql('ALTER TABLE order_item_group ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_item_group ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item_service ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_item_service ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item_service ALTER worker_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_item_service ALTER worker_id DROP DEFAULT');
        $this->addSql('ALTER TABLE penalty ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE penalty ALTER transaction_id TYPE BIGINT');
        $this->addSql('ALTER TABLE penalty ALTER transaction_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_afe28fd82fc0cb0f RENAME TO idx_16562_idx_afe28fd82fc0cb0f');
        $this->addSql('ALTER TABLE wallet ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE salary ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE salary ALTER income_id TYPE BIGINT');
        $this->addSql('ALTER TABLE salary ALTER income_id DROP DEFAULT');
        $this->addSql('ALTER TABLE salary ALTER outcome_id TYPE BIGINT');
        $this->addSql('ALTER TABLE salary ALTER outcome_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_9413bb71e6ee6d63 RENAME TO idx_16574_idx_9413bb71e6ee6d63');
        $this->addSql('ALTER INDEX idx_9413bb71640ed2c0 RENAME TO idx_16574_idx_9413bb71640ed2c0');
        $this->addSql('ALTER TABLE order_item ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_item ALTER order_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_item ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER parent_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_item ALTER parent_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_item ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER type TYPE BIGINT');
        $this->addSql('ALTER TABLE order_item ALTER type DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_52ea1f098d9f6d38 RENAME TO idx_16500_idx_52ea1f098d9f6d38');
        $this->addSql('ALTER INDEX idx_52ea1f09727aca70 RENAME TO idx_16500_idx_52ea1f09727aca70');
        $this->addSql('ALTER TABLE order_salary ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_salary ALTER order_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_salary ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_salary ALTER transaction_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_salary ALTER transaction_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_579caba48d9f6d38 RENAME TO idx_16550_idx_579caba48d9f6d38');
        $this->addSql('ALTER INDEX idx_579caba42fc0cb0f RENAME TO idx_16550_idx_579caba42fc0cb0f');
        $this->addSql('ALTER TABLE wallet_transaction ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE wallet_transaction ALTER recipient_id TYPE BIGINT');
        $this->addSql('ALTER TABLE wallet_transaction ALTER recipient_id DROP DEFAULT');
        $this->addSql('ALTER TABLE wallet_transaction ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE wallet_transaction ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_7daf972e92f8f78 RENAME TO idx_16588_idx_7daf972e92f8f78');
        $this->addSql('ALTER TABLE order_payment ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_payment ALTER order_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_payment ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_payment ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_payment ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_9b522d468d9f6d38 RENAME TO idx_16538_idx_9b522d468d9f6d38');
        $this->addSql('ALTER TABLE order_suspend ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_suspend ALTER order_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_suspend ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_suspend ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_suspend ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_c789f0d18d9f6d38 RENAME TO idx_16556_idx_c789f0d18d9f6d38');
        $this->addSql('ALTER TABLE order_note ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_note ALTER order_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_note ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_note ALTER created_by_id TYPE BIGINT');
        $this->addSql('ALTER TABLE order_note ALTER created_by_id DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_824cc0038d9f6d38 RENAME TO idx_16529_idx_824cc0038d9f6d38');
    }
}
