doctrine:
    orm:
        mappings:
            created_by:
                type: annotation
                prefix: App\CreatedBy\Entity
                dir: '%kernel.project_dir%/src/CreatedBy/Entity'
