version: '3.7'

services:
    traefik:
        image: traefik:v1.7.4-alpine
        command:
            - --api
#            - --debug
            - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
            - --entrypoints=Name:https Address::443 TLS
            - --defaultentrypoints=http,https
            - --acme
            - --acme.storage=/etc/traefik/acme.json
            - --acme.entryPoint=https
            - --acme.httpChallenge.entryPoint=http
            - --acme.onHostRule=true
            - --acme.onDemand=false
            - --acme.email=me@grachevko.ru
            - --docker
            - --docker.swarmMode
            - --docker.domain=traefik
            - --docker.watch
        ports:
            -
                target: 80
                published: 80
                mode: host
            -
                target: 443
                published: 443
                mode: host
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/traefik:/etc/traefik
        networks:
            - ingress
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == manager
            update_config:
                parallelism: 1
                delay: 10s
                order: stop-first
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.docker.network=proxy"
                - "traefik.enable=true"
                - "traefik.frontend.rule=Host:traefik.automagistre.ru"
                - "traefik.frontend.auth.digest.users=preemiere:traefik:7aac7340f53bb28f1cb22efc7205dc37,kach:traefik:1ccd02b48e1c4026fdd8df878cb5c250"
                - "traefik.port=8080"
                - "traefik.protocol=http"
                - "traefik.backend.loadbalancer.method=wrr"

networks:
    ingress:
        driver: overlay
        attachable: true
        name: proxy
