easy_admin:
    entities:
        Income:
            class: App\Income\Entity\Income
            controller: App\Income\Controller\IncomeController
            disabled_actions: ['delete', 'search']
            templates:
                list: 'easy_admin/income/list.html.twig'
                show: 'easy_admin/income/show.html.twig'
            list:
                title: 'Приходы'
                actions:
                    - { name: 'pay', template: 'easy_admin/income/action_pay.html.twig' }
                fields:
                    - { property: 'supplierId', label: 'Поставщик', template: 'easy_admin/field_identifier.html.twig', target: _self }
                    - { property: 'status', vritual: true, label: 'Статус', template: 'easy_admin/income/field_status.html.twig' }
                    - { property: 'totalPrice', label: 'Сумма', template: 'easy_admin/field_money.html.twig' }
                    - { property: 'itemsCount', label: 'Позиций' }
                    - { property: 'accruedAt', label: 'Принято' }
            form:
                fields:
                    - { property: 'supplierId', label: 'Поставщик', type: App\Customer\Form\SellerType, type_options: { required: true } }
                    - { property: 'document', label: 'Документ' }
            new:
                title: 'Создать приход'
            edit:
                title: 'Редактировать приход'
            show:
                title: 'Приход'
                fields:
                    - { property: 'supplierId', label: 'Поставщик', template: 'easy_admin/field_identifier.html.twig' }
                    - { property: 'document', label: 'Документ' }
                    - { property: 'incomeParts', label: 'Позиции', template: 'easy_admin/income/field_income_parts.html.twig' }
                    - { property: 'totalPrice', label: 'Сумма', template: 'easy_admin/field_money.html.twig' }
                    - { property: 'accruedAt', label: 'Принято' }
                    - { property: 'accruedBy', label: 'Принял', template: 'easy_admin/field_user.html.twig', type: 'text' }

        IncomePart:
            class: App\Income\Entity\IncomePart
            controller: App\Income\Controller\IncomePartController
            form:
                fields:
                    -   property: 'partId'
                        label: 'Запчасть'
                        type: App\Part\Form\PartAutocompleteType
                    - { property: 'price', label: 'Цена', type: App\Form\Type\MoneyType }
                    - { property: 'quantity', label: 'Количество', type: App\Form\Type\QuantityType }
            new:
                title: 'Создать новую Запчасть для прихода от {{ entity.incomeId|display_name }}'
            edit:
                title: 'Редактировать Запчасть для прихода от {{ entity.income.toId()|display_name }}'
                fields:
                    -   property: 'partId'
                        type_options:
                            disabled: true
