name: Dependabot auto-merge
on: pull_request_target
jobs:
    dependabot:
        runs-on: ubuntu-latest
        if: github.actor == 'dependabot[bot]'
        steps:
            -   name: Checkout PR
                uses: actions/checkout@v2
            -   name: Enable auto-merge for Dependabot PRs
                run: gh pr merge --auto --rebase "${{github.event.pull_request.number}}"
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
